<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookings [
<!ELEMENT bookings (booking*)>
    <!ATTLIST bookings member CDATA "">
    <!ATTLIST bookings export-date CDATA "0000-00-00">
    <!ELEMENT booking (activity, location, date, time)>
    <!ATTLIST booking Id CDATA "">
    <!ELEMENT activity (#PCDATA)>
    <!ELEMENT location (#PCDATA)>
    <!ELEMENT date (#PCDATA)>
    <!ELEMENT time (#PCDATA)>
]>


<bookings member="Max" export-date="2025-05-10" >

  <booking Id="100">
    <activity>"Zumba"</activity>
    <location>"Ashgrove"</location>
    <date>2025-05-10</date>
    <time>17:00</time>
  </booking>
  
</bookings>